#!/bin/bash

cd ~/.i3
cat config-general > config

for DISPLAY in $(xrandr | grep " connected" | grep "mm" | cut -d' ' -f1); do
	echo "$DISPLAY..."
	if [ -f config-$DISPLAY ]; then
		cat config-$DISPLAY >> config
	else
		cat config-template >> config
		sed -i "s/DISPLAYNAME/$DISPLAY/g" config
	fi
done

i3-msg restart
