#!/bin/bash

SCREEN="screen -AOxRR $USER; sleep 100"
NAME="URxvt"
COMMAND=

REMOTE_SERVER=$(cat ~/.smowterm | cut -d " " -f 1)

check_server() {
	return # not checking
	if ( ! ping -c 1 -w 5 "$1" &>/dev/null ); then
		echo "Server ($1) unreachable." && sleep 10 && exit 1
	fi
}

while getopts ":b" OPTION
do
	case $OPTION in
		b)
			NAME="${NAME}Big"
			shift $((OPTIND-1))
			;;
	esac
done

case $1 in
	""|local)
		COMMAND=$SCREEN
		;;

	gui)
		ANS=$(zenity --list --text='Pick a server' --column=servers local $REMOTE_SERVER)
		[[ -n $ANS ]] && $0 $ANS
		exit 0
		;;

	*)
		check_server $1
		NAME="${NAME}Remote"
		if [ -n "$(cat ~/.smowterm | grep $1 | grep mosh)" ]; then
			COMMAND="mosh --ssh='ssh -X' $1 -- $SCREEN"
		else
			COMMAND="ssh -tX $1 $SCREEN"
		fi
		;;
esac

urxvtc -name $NAME -e sh -c "$COMMAND"

sleep 10
