#!/bin/bash

clean_clock() {
	read INPUT
	echo $INPUT | sed 's, [0]\+, ,g'
}

HOME_TIME="$(TZ=America/Sao_Paulo date +%Hh%M)"
CURR_TIME="$(date +%Hh%M)"

OUTPUT=$(date +"%a, %b %d " | clean_clock)
OUTPUT+=$(~/scripts/all/unicode $(date +" %j" | clean_clock))
OUTPUT+=" $(echo $CURR_TIME | clean_clock)"
[ "$HOME_TIME" != "$CURR_TIME" ] && OUTPUT+=" ($(echo $HOME_TIME | clean_clock))"

echo "$OUTPUT"
echo ""
echo ""
