#!/bin/bash

clean_clock() {
	echo ""
}

HOMETZ=America/Sao_Paulo

#OUTPUT=$(date +"%a, %b %d (%j) %Hh%M" | sed 's, 0, ,g;s,([0]\+,(,g')
OUTPUT=$(date +"%a, %b %d " | sed 's, [0]\+, ,g')
OUTPUT+=$(~/scripts/utils/unicode $(date +" %j" | sed 's, [0]\+, ,g'))
OUTPUT+=$(date +" %Hh%M" | sed 's, [0]\+, ,g')

grep -q $HOMETZ /etc/timezone \
	|| OUTPUT+=" ($(TZ=America/Sao_Paulo date +%Hh%M))"

echo "$OUTPUT"
echo ""
echo ""
