#!/bin/bash

case $BLOCK_BUTTON in
	3) deja-dup-preferences ;;  # click
	4) echo "scroll up" ;;  # scroll up
	5) echo "scroll down" ;;  # scroll down
esac

BACKUP_DIR=$(dconf read /org/gnome/deja-dup/file/path)
LAST_BACKUP=$(date +%s --date=$(dconf read /org/gnome/deja-dup/last-backup | tr -d \'))

let "DIFF= $(date +%s) - $LAST_BACKUP"
let "DAYS=$DIFF / 86400"
let "HOURS=($DIFF - $DAYS * 86400) / 3600"

if [ "$DAYS" -gt 3 ]; then
   	echo "${DAYS}d"
	echo "${DAYS}d"
	[ "$DAYS" -ge 5 ] && ( [ "$DAYS" -ge 10 ] && echo "#FF0000" || echo "#FFFF00" ) || echo "#FFFFFF"
fi
