#!/bin/bash

TMPFILE=/tmp/mouse_move
SCREENSAVER_TIMEOUT=300
SHOW_VALUE=60

CURR_MOVE=$(xdotool getmouselocation 2> /dev/null)
CURR_TIME=$(date +%s)

if [ -f $TMPFILE ]; then
	LAST_MOVE=$(cat $TMPFILE 2> /dev/null)
	LAST_TIME=$(find $TMPFILE -printf "%T@" | cut -d. -f1)
	[ "$LAST_MOVE" != "$CURR_MOVE" ] && rm $TMPFILE && exit
else
	LAST_MOVE=$CURR_MOVE
	LAST_TIME=$CURR_TIME
	echo $CURR_MOVE > $TMPFILE
fi

let "TIMEOUT=$SCREENSAVER_TIMEOUT - ($CURR_TIME - $LAST_TIME)"

[ "$TIMEOUT" -gt $SHOW_VALUE ] && exit
echo "${TIMEOUT}s"
echo ""
[ "$TIMEOUT" -lt "$(expr $SHOW_VALUE / 2)" ] && echo "#FF0000" || echo "#FFFF00"

#I3BLOCKS=$(pgrep i3blocks)
#[ -n "$I3BLOCKS" ] && sleep 3 && kill -45 $I3BLOCKS
