#!/bin/bash

FULL_TEXT=
SHORT_TEXT=
COLOR=
EXITCODE=0
IPCMD="/sbin/ip"

HOST_TO_TEST=google.com
LOG=/tmp/check_network
IGNORED=0

OLDIFS=$IFS
IFS=$'\n'
for IF in $($IPCMD -o -4 a); do
	NAME=$(echo $IF | awk '{ print $2 }')
	case $NAME in
		lo|virbr*|docker*|br-*) let IGNORED=IGNORED+1 && continue ;;
	esac

	if [ "$(iwgetid | cut -d' ' -f1)" = "$NAME" ]; then
		SUFFIX=" ($(iwgetid -r))"
	else
		SPEED="$(cat /sys/class/net/$NAME/speed 2> /dev/null | bc)"
		[ $SPEED -gt 1000 ] \
			&& SUFFIX=" ($(( $SPEED/1000 ))G)" || SUFFIX=" (${SPEED}M)"
	fi

	IP=$(echo $IF | awk '{ print $4 }')
	SHORT_TEXT+="$(echo $IP | cut -d/ -f1)  "
	FULL_TEXT+="${IP}${SUFFIX}  "
done
IFS=$OLDIFS

[ $IGNORED -gt 0 ] && FULL_TEXT+="+$IGNORED"
FULL_TEXT=$(echo "$FULL_TEXT" | sed 's/^ *//; s/ *$//')
SHORT_TEXT=$(echo "$SHORT_TEXT" | sed 's/^ *//; s/ *$//')

if ! ping -c 1 -W 5 $HOST_TO_TEST > /dev/null 2>&1; then
	[ ! -f "$LOG" ] && date +%s > $LOG

	DIFF=$(echo $(( $(date +%s) - $(cat $LOG) )) | bc)
	if   [ $DIFF -gt 86400 ]; then TIME="$(( $DIFF / 86400 ))d"
	elif [ $DIFF -gt  3600 ]; then TIME="$(( $DIFF /  3600 ))h"
	elif [ $DIFF -gt    60 ]; then TIME="$(( $DIFF /    60 ))min"
	else TIME="${DIFF}s"; fi

	if [ -z "$(echo $FULL_TEXT | xargs)" ]; then
		FULL_TEXT=" No Network ($TIME) "
		EXITCODE=33
	else
		FULL_TEXT="$TIME  $FULL_TEXT"
		COLOR=#ff0000
	fi
else
	[ -f "$LOG" ] && rm $LOG
fi

echo "$FULL_TEXT"
echo "$SHORT_TEXT"
echo "$COLOR"
exit $EXITCODE
