#!/bin/bash

complement() {
	if [ "$(iwgetid | cut -d' ' -f1)" = "$1" ]; then
		echo " ($(iwgetid -r))"
	else
		SPEED="$(cat /sys/class/net/$1/speed 2> /dev/null)"
		[ -n "$SPEED" ] && echo " ($SPEED Mbps)"
	fi
}

FULL_TEXT=
SHORT_TEXT=
COLOR=

OLDIFS=$IFS
IFS=$'\n'
for IF in $(ip -o -4 a); do
	NAME=$(echo $IF | awk '{ print $2 }')
	IP=$(echo $IF | awk '{ print $4 }' | cut -d/ -f1)

	case $NAME in
		lo|virbr*|docker*) continue ;;
		em*)         ICON= ;; # ethernet
		enp0s26u1u2) ICON= ;; # usb
		tun*)        ICON= ;; # tunnel
		wlp3s0)      ICON= ;; # wireless
		*)           ICON= ;; # others
	esac
	FULL_TEXT+="$IP$(complement $NAME)   "
	SHORT_TEXT+="$IP   "
done
IFS=$OLDIFS

if [ -z "$(echo $FULL_TEXT | xargs)" ]; then
   FULL_TEXT="no networks"
   COLOR="#ff0000"
fi

echo "$FULL_TEXT" | sed 's/^ *//; s/ *$//'
echo "$SHORT_TEXT" | sed 's/^ *//; s/ *$//'
echo "$COLOR"
