#!/bin/bash

# Copyright (C) 2015 Paulo Flabiano Smorigo <pfsmorigo@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Stopwatch and countdown v1.0

# Right click to start the clock. If the clock is 00:00 you will be in
# stopwatch mode (S). Use your scroll wheel to increase (and decrease)
# the clock and use it as a countdown timer (C). Right click when your
# counter is on will pause it.

TIME_FRACTION=${1:-300}
TIME_FORMAT=${2:-%H:%M:%S}

STORE_FILE=/tmp/i3blocks_stopwatch_countdown
NOW=$(date +%s)

# load values from the file if exists
[ -f $STORE_FILE ] && IFS=, read MODE COUNTER EPOCH < $STORE_FILE

# sanity check and reset it if necessary
[[ $MODE =~ ^(C|S)$ ]] || MODE=C
[[ $COUNTER =~ ^-?[0-9]+$ ]] || COUNTER=0
[[ $EPOCH =~ ^-?[0-9]+$ ]] || EPOCH=0

# event handler
case $BLOCK_BUTTON in
	3) # right click
		if [ $EPOCH == 0 ]; then
			case $MODE in
				S) EPOCH=$(expr $NOW - $COUNTER) ;;
				C) EPOCH=$(date -d "$COUNTER sec" +%s) ;;
			esac
		else
			EPOCH=0
		fi
		;;

	4|5) # scroll up or scroll down
		[ $BLOCK_BUTTON = 4 ] && OP=+ || OP=-

		# update the counter
		let "COUNTER = $COUNTER $OP $TIME_FRACTION"

		# change mode depending on the counter value
		[ $COUNTER -le 0 ] && MODE=S || MODE=C

		# stop the clock
		EPOCH=0
		;;
esac

# update counter if is on
if [ $EPOCH -gt 0 ]; then
	case $MODE in
		S) let "COUNTER = $NOW - $EPOCH" ;;
		C) let "COUNTER = $EPOCH - $NOW" ;;
	esac
fi

# stop the clock if it reaches the target
[ $COUNTER -lt 0 ] && COUNTER=0

# store the current state
echo "$MODE,$COUNTER,$EPOCH" > $STORE_FILE

# print
echo "$MODE $(date -u -d @$COUNTER +$TIME_FORMAT)"
echo ""
[ $MODE == C ] && [ $COUNTER -eq 0 ] && [ $EPOCH -ne 0 ] && exit 33
[ $EPOCH -eq 0 ] && echo "#ffffff" || echo "#00ff00"
