#!/bin/bash

RASP_DIR=/proc/device-tree/model

if [ -e "$RASP_DIR" ] && [[ "$(cat $RASP_DIR)" =~ "Raspberry" ]]; then
	TEMPERATURE=$(/opt/vc/bin/vcgencmd measure_temp | cut -d= -f2 | cut -d. -f1)
else
	TEMPERATURE=$(acpi -t | head -n1 | awk '{ print $4 }' | cut -d. -f1)
fi

[ "$TEMPERATURE" -gt 70 ] && COLOR="#ffff00"
[ "$TEMPERATURE" -gt 85 ] && COLOR="#ff0000"

echo "${TEMPERATURE}°C"
echo ""
echo "$COLOR"
