#!/bin/bash

UPDATE_COUNT=$(yum check-update 2> /dev/null | grep "updates$" | wc -l)

if [ $UPDATE_COUNT -gt 0 ]; then
   echo -n "$UPDATE_COUNT update"
   [ $UPDATE_COUNT -gt 1 ] && echo "s" || echo ""
   echo "${UPDATE_COUNT}u"
   echo "#ffff00"
fi
