#!/bin/bash

DOWNLOAD_DIR="$HOME/Downloads"
DATE_DIR=$DOWNLOAD_DIR/$(date +%F)
FILE_LIST="$(find $DOWNLOAD_DIR -maxdepth 1 -type f)"

IFS=$'\n'
if [ -z "$FILE_LIST" ]; then
	echo "There is no file!"
else
	mkdir -p $DATE_DIR
	for FILE in $FILE_LIST; do
		mv "$FILE" $DATE_DIR
	done
fi

