#!/bin/bash

SCREEN_ARRAY=
COUNT=

while [ 1 ]; do
	SCREEN_LIST=$(ls -1 /var/run/screen/S-$USER | sort -h)
	COUNT=0
	screen -wipe > /dev/null 2>&1

	echo ""
	for SCREEN in $SCREEN_LIST; do
		COUNT=$(( $COUNT + 1 ))
		SCREEN_ARRAY[$COUNT]=$SCREEN
		printf " %2s) %s\n" $COUNT $SCREEN
	done
	echo ""

	read -p "Pick one: " PICK
	[ "$PICK" = "x" ] && exit
	screen -x ${SCREEN_ARRAY[$PICK]}
done
