#!/bin/bash

if ! command -v realpath >/dev/null 2>&1; then
	echo"You need to install realpath package!"
	exit 1
fi

create_symlinks() {
	DIR=$(dirname $(realpath $0))
	echo [$DIR]

	for FILE in $(ls $DIR); do
		[ $FILE = README.md ] && continue

		echo "Creating $FILE symlink in ~/bin..."
		ln -fs $DIR/$FILE ~/bin/$FILE
	done
}

create_symlinks






