#!/bin/bash

server_list()
{
	HOSTS="$(grep -v "^#" /etc/hosts | awk '{ print $2 }' | sort -u)"
	SSH_CONFIG="$(grep "^Host" ~/.ssh/config | awk '{ print $2 }' | grep -v '*' )"
	echo -e "$HOSTS\n$SSH_CONFIG" | sort -u
}

pick_server() {
	ANS=$(zenity --list --text='Pick a server' --column=servers local $(server_list))
	[[ -n $ANS ]] && $0 $ANS
	exit 0
}

while getopts ":bs" OPTION
do
	case $OPTION in
		b) NAME+="Big" ;;
		s) NAME+="Small" ;;
	esac
	shift $((OPTIND-1))
done

case $1 in
	gui) pick_server;;
	*) TARGET=$1;;
esac

if [ -n "$2" ]; then
	SCREEN_NAME=$2
fi

NAME="URxvt"

# no target means local host
if [ -z "$TARGET" ] || [ "$TARGET" = "local" ]; then
	COMMAND="smowscreen $SCREEN_NAME"
else
	TARGET_OPTIONS=$(grep "$TARGET " ~/.smowterm | cut -d' ' -f2- | xargs)
	NAME+="Remote"
	[[ "$TARGET_OPTIONS" =~ "mosh" ]] && COMMAND="mosh" || COMMAND="ssh"
	COMMAND+=" $TARGET"

	if [[ "$TARGET_OPTIONS" =~ "smowscreen" ]]; then
		COMMAND+=" -- bash ~/bin/smowscreen $SCREEN_NAME"
	elif [[ "$TARGET_OPTIONS" =~ "screen" ]]; then
		COMMAND+=" -- screen -AOxRR $USER"
	fi
fi

urxvtc -name $NAME -e sh -c "$COMMAND"; sleep 100
#urxvtc -name $NAME -e sh -c "export TERM='linux'; $PREFIX; sleep 100"

sleep 10
