#!/bin/bash

server_list()
{
	HOSTS="$(grep -v "^#" /etc/hosts | awk '{ print $2 }' | sort -u)"
	SSH_CONFIG="$(grep "^Host" ~/.ssh/config | awk '{ print $2 }' | grep -v '*' )"
	echo -e "$HOSTS\n$SSH_CONFIG" | sort -u
}

pick_server() {
	ANS=$(zenity --list --text='Pick a server' --column=servers $(server_list))
	[[ -n $ANS ]] && $0 $ANS
	exit 0
}

while getopts ":bs" OPTION
do
	case $OPTION in
		b) NAME+="Big" ;;
		s) NAME+="Small" ;;
	esac
	shift $((OPTIND-1))
done

case $1 in
	gui) pick_server;;
	*) TARGET=$1;;
esac

NAME="URxvt"

if [ -n "$TARGET" ]; then
	TARGET_OPTIONS=$(grep "$TARGET " ~/.smowterm | cut -d' ' -f2- | xargs)
	NAME+="Remote"
	[[ "$TARGET_OPTIONS" =~ "mosh" ]] && PREFIX="mosh" || PREFIX="ssh"
	PREFIX+=" $TARGET -- "
fi

urxvtc -name $NAME -e sh -c \
	"$PREFIX smowscreen || screen -AOxRR $USER || bash"; sleep 100
#urxvtc -name $NAME -e sh -c "export TERM='linux'; $PREFIX; sleep 100"

sleep 10
