#!/bin/bash

base_dir() {
	EXEC=${BASH_SOURCE[0]}
	if [ -h $EXEC ]; then
		LINK="$(readlink $EXEC)"
		[ "${LINK:0:1}" = "/" ] && EXEC="$LINK" || EXEC="$(dirname $EXEC)/$LINK"
	fi
	echo "$(cd $(dirname $EXEC); pwd)"
}

initial_dirs() {
	mkdir -p ~/bin
}

backup() {
	BACKUP_DIR=~/Private/Backup/Linux
	cd $BACKUP_DIR
	check_private
	echo -e "\nBackup\n-----------------------------------"
	rsync -avz --delete --progress ~/.local/share/shotwell/data/* $BACKUP_DIR/Shotwell
	git add .
	git commit -q -m "backup shotwell"
	rsync -avz --delete --progress ~/Dropbox/KeePassX/* $BACKUP_DIR/KeePassX
	git add .
	git commit -q -m "backup keepassx"
}

check_private() {
	if test -f ~/Private/README.txt; then
		echo -e "\nMounting Private\n-----------------------------------"
		ecryptfs-mount-private
		if test -f ~/Private/README.txt; then
			echo "Unable to open Private!"
			exit 1
		fi
	fi
}

if ! command -v realpath >/dev/null 2>&1; then
	echo "You need to install realpath package!"
	exit 1
fi

BASE_DIR="$(base_dir)"

SYMLINK_EXEC=symlink2bin
if ! command -v $SYMLINK_EXEC >/dev/null 2>&1; then
	if [ -f $BASE_DIR/$SYMLINK_EXEC ]; then
		SYMLINK_EXEC="$BASE_DIR/$SYMLINK_EXEC"
	else
		echo "Symlink executable not found!"
		exit 1
	fi
fi

case $1 in

	backup)
		backup
		;;

	*)
		$BASE_DIR/dotfiles
		$SYMLINK_EXEC ~/bin $(find $BASE_DIR -maxdepth 1 -mindepth 1 -executable -type f)
		$SYMLINK_EXEC ~/bin $BASE_DIR/smartprompt/smartprompt
		;;
esac

echo -e "\nDone.\n"
