#!/bin/bash

if ! command -v realpath >/dev/null 2>&1; then
	echo"You need to install realpath package!"
	exit 1
fi

create_symlinks() {
	mkdir -p ~/bin
	echo -e "\nCreating symlinks\n-----------------------------------"
	DIR=$(dirname $(realpath $0))

	for FILE in $(find $DIR -type f -executable -not -iwholename '*.git*' | sort); do
		FILE=$(echo $FILE | sed "s,${DIR}\/,,g")

		echo "Creating $(basename $FILE) symlink in ~/bin..."
		ln -fs $DIR/$FILE ~/bin/$(basename $FILE)
	done
}

backup() {
	BACKUP_DIR=~/Private/Backup/Linux
	cd $BACKUP_DIR
	check_private
	echo -e "\nBackup\n-----------------------------------"
	rsync -avz --delete --progress ~/.local/share/shotwell/data/* $BACKUP_DIR/Shotwell
	git add .
	git commit -q -m "backup shotwell"
	rsync -avz --delete --progress ~/Dropbox/KeePassX/* $BACKUP_DIR/KeePassX
	git add .
	git commit -q -m "backup keepassx"
}

check_private() {
	if test -f ~/Private/README.txt; then
		echo -e "\nMounting Private\n-----------------------------------"
		ecryptfs-mount-private
		if test -f ~/Private/README.txt; then
			echo "Unable to open Private!"
			exit 1
		fi
	fi
}

case $1 in

	backup)
		backup
		;;

	*)
		create_symlinks
		;;
esac

echo -e "\nDone.\n"
