#!/bin/bash

server_list()
{
	HOSTS="$(grep -v "^#" /etc/hosts | awk '{ print $2 }' | sort -u | xargs)"
	SSH_CONFIG="$(grep "^Host" ~/.ssh/config | awk '{ print $2 }')"
	echo $HOSTS $SSH_CONFIG | sort -u | xargs
}

if [ "$1" = "gui" ]; then
	ANS=$(zenity --list --text='Pick a server' --column=servers $(server_list))
	[[ -n $ANS ]] && $0 $ANS
	exit 0
fi

while getopts ":bs" OPTION
do
	case $OPTION in
		b) NAME+="Big" ;;
		s) NAME+="Small" ;;
	esac
	shift $((OPTIND-1))
done

TARGET=$1
NAME="URxvt"
COMMAND=

if [ -n "$TARGET" ]; then
	TARGET_OPTIONS=$(grep "$TARGET " ~/.smowterm | cut -d' ' -f2- | xargs)
	NAME+="Remote"

	if [[ "$TARGET_OPTIONS" =~ "mosh" ]]; then
		COMMAND="mosh --ssh='ssh -X' $TARGET -- "
	else
		COMMAND="ssh -tY $TARGET -- "
	fi
fi

COMMAND+="screen -AOxRR $USER \|\| bash"

urxvtc -name $NAME -e sh -c "$COMMAND; sleep 100"
#urxvtc -name $NAME -e sh -c "export TERM='linux'; $COMMAND; sleep 100"

sleep 10
