#!/bin/bash

DISTRO=$(head -n1 /etc/issue | cut -d ' ' -f 1)
PACKAGES=

distro_install() {
	[ "$DISTRO" = "Fedora" ] && INSTALLER="sudo yum install"
	[ "$DISTRO" = "Debian" ] && INSTALLER="sudo apt-get install"

	# common packages
	PACKAGES+="vim screen mosh git"

	if [ "$DISTRO" = "Fedora" ]; then
		PACKAGES+="@development-tools git-cvs"
		PACKAGES+="acpid"                   # for dock detection
		PACKAGES+="istanbul"                # screen capture
		PACKAGES+="julius"                  # voice recognition
		PACKAGES+="julius-voxforge"         # voice recognition
		PACKAGES+="kpcli"                   # keepassx cli tool
		PACKAGES+="perl-LWP-Protocol-https" # so rt can access https
		PACKAGES+="poppler-utils"           # extract images from pdf
		PACKAGES+="python-keyring"          # use keyring in scripts
		PACKAGES+="rt"                      # request tracker
		PACKAGES+="sox"                     # audio tools (used by bin/monitor_audio)
		PACKAGES+="libproxy-python"         # gsharkdown
		PACKAGES+="openswan"                # mtsconnect
	fi

	$INSTALLER $PACKAGES
}

distro_install

