#!/bin/bash

SCREEN_LS="$(screen -ls)"
SCREEN_LIST=$(echo "$SCREEN_LS" | grep "tached)$" | awk '{ print $1 }' | cut -d. -f2 | xargs)
SCREEN_CURRENT=$(echo $STY | cut -d. -f2)

SCREEN_ARRAY=
COUNT=0

if [ -z "$1" ]; then
	[ -z "$SCREEN_LIST" ] && SCREEN_LIST=$USER

	echo ""
	for SCREEN in $SCREEN_LIST; do
		COUNT=$(( $COUNT + 1 ))
		SCREEN_ARRAY[$COUNT]=$SCREEN
		printf " %2s) %s\n" $COUNT $SCREEN
	done
	echo ""

	read -p "Pick one (x to quit, n for new): " PICK
	if [ "$PICK" = "x" ]; then
		exit
	elif [[ "$PICK" =~ ^[0-9]+$ ]]; then
		SCREEN_SELECTED=${SCREEN_ARRAY[$PICK]}
	else
		SCREEN_SELECTED=$PICK
	fi
else
	SCREEN_SELECTED=$1
fi

if [ "$SCREEN_SELECTED" != "$SCREEN_CURRENT" ]; then
	screen -AOxRR $SCREEN_SELECTED
else
	echo "Already in $SCREEN_CURRENT"
fi
