#!/bin/bash

usage() {
	echo ""
	echo "Usage: $(basename $0) [OPTION]... DESTINY FILES..."
	echo ""
	echo "Options:"
	echo "  -p    prefix of the symlink"
	echo "  -d    dry-run"
	echo ""
}

relative_dir() {
	COMMON_PART=$1
	BACK=
	while [ "${2#$COMMON_PART}" = "${2}" ]; do
		COMMON_PART=$(dirname $COMMON_PART)
		BACK="../${BACK}"
	done
	echo "${BACK}${2#$COMMON_PART/}"
}

while getopts p:d OPT; do
	case $OPT in
		p) PREFIX=$OPTARG ;;
		d) DRYRUN=1;;
	    *) usage; exit ;;
	esac
done
shift $((OPTIND-1))
OPTIND=0

[ -z "$2" ] && echo "Missing parameters!" && usage && exit 1
[ ! -d "$1" ] && echo "Directory $1 doesn't exist" && exit 2

DESTINY=$(cd $1; pwd)
shift

for FILE in $*; do
	FILE_NAME=$(basename $FILE)
	FILE_PATH=$(cd $(dirname $FILE); pwd)

	FILE_DEST="$DESTINY/${PREFIX}$FILE_NAME"
	[ -e $FILE_DEST ] && [ ! -h $FILE_DEST ] && mv $FILE_DEST{,\_$(date +%F_%H-%M-%S)}

	COMMAND="ln -fs $(relative_dir $DESTINY $FILE_PATH)/$FILE_NAME $FILE_DEST"
	echo $COMMAND
	[ -z "$DRYRUN" ] && $COMMAND
done
