#!/bin/bash -e

log() {
	PROJECT=$1
	shift
	LOG_TEXT="$*"
	echo "taskassist: $PROJECT $LOG_TEXT"
	echo "$(date +"%F %T") $LOG_TEXT" >> $PROJECT_DIR/$PROJECT/.taskassist
}

PROJECT_DIR=$HOME/Projects
PROJECT_DIR_ARCHIVE=$PROJECT_DIR/.done
PROJECT_LIST=$(task projects | tail -n +5 | head -n -2 | cut -d' ' -f1 | xargs)

mkdir -p $PROJECT_DIR $PROJECT_DIR_ARCHIVE
cd $PROJECT_DIR

# check if a done project was opened again
for PROJECT in $PROJECT_LIST; do
	if [ -d $PROJECT_DIR_ARCHIVE/$PROJECT ]; then
		mv $PROJECT_DIR_ARCHIVE/$PROJECT $PROJECT_DIR
		log $PROJECT reopened
	fi
done

# archive done projects
for DIR in *; do
	if [[ ! $PROJECT_LIST =~ $DIR ]]; then
		if [ -n "$(find $DIR -mindepth 1)" ]; then
			log $DIR closed
			mv $PROJECT_DIR/$DIR $PROJECT_DIR_ARCHIVE
		else
			echo "taskassist: $DIR removed (empty)"
			rmdir $DIR
		fi
	fi
done

# create dir for "new" projects
mkdir -p $PROJECT_LIST
