#!/bin/bash

# https://www.droidwin.com/debloat-remove-bloatware-from-samsung-devices-via-adb/
# https://r1.community.samsung.com/t5/others/how-to-remove-samsung-bloatware-without-root/td-p/5817510

install() {
	run adb shell cmd package install-existing $1
}

uninstall() {
	run adb shell pm uninstall --user 0 $1
}

run() {
	echo $*
	$*
}

backup() {
	DEVICE="$(adb devices -l | awk '{ print $5 }' | cut -d: -f2 | sed '/^$/d')"
	BACKUP_FILE="$HOME/backup/android/$(date +%F_%H-%M-%S)_$DEVICE.ab"
	set -x
	#adb backup -apk -shared -f $BACKUP_FILE $APP_LIST
	sudo adb backup -f $BACKUP_FILE $APP_LIST
}

unpack() {
	FILE=$1
	[ ! -f "$FILE" ] && echo "File not found" && exit 1
	set -x
	sudo dd if=$FILE bs=24 skip=1 | openssl zlib -d > ${FILE%.*}.tar
}

read -d '' APP_LIST <<-EOF
com.samsung.android.calendar,Samsung Calendar
com.sec.android.gallery3d,Gallery
EOF

case $1 in
	install|uninstall) ;;
	#backup|unpack) $* ;;
	'') echo "Need a subcommand!" && exit 1 ;;
	*) echo "Invalid command" && exit 1 ;;
esac

echo ""
COUNT=0
OLDIFS=$IFS
IFS=$'\n'
for ITEM in $APP_LIST; do
	COUNT=$(( $COUNT + 1 ))
	APP=${ITEM#*,}
	ADR=${ITEM%,*}
	APP_ARRAY[$COUNT]=$ADR
	printf "%5s) %s\n" $COUNT $APP
done
IFS=$OLDIFS
echo ""

read -p "Pick one: " PICK
[ -z "$PICK" ] && exit

echo ""
$1 ${APP_ARRAY[$PICK]}
