#!/bin/bash
#
EXEC=$(find /home/resources/appimage -iname "$(basename $0)*" | sort | tail -1)

case $(basename $0) in
	creality_print)
		__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia $EXEC
		;;
	*)
		QT_SCALE_FACTOR=1.25 $EXEC
		;;
esac
