#!/bin/bash

COMMAND=$1
shift

case $COMMAND in
	print)
		su root -c "echo $* > /dev/kmsg"
		;;

	human)
		$(type -P dmesg) "$@" | perl -w -e 'use strict;
		my ($uptime) = do { local @ARGV="/proc/uptime";<>}; ($uptime) = ($uptime =~ /^(\d+)\./);
		foreach my $line (<>) {
			printf( ($line=~/^\[\s*(\d+)\.\d+\](.+)/) ? ( "[%s]%s\n", scalar localtime(time - $uptime + $1), $2 ) : $line )
		}'
		;;

	*)
		echo "What?"
		exit 1
		;;
esac
