#!/bin/bash -x

chmod 700 ~/.config/gnupg
chmod 700 ~/.ssh

chmod 600 ~/.ssh/id_rsa
chmod 600 ~/.ssh/keys/*

chmod 644 ~/.ssh/authorized_keys
chmod 644 ~/.ssh/config
chmod 644 ~/.ssh/id_rsa.pub
chmod 644 ~/.ssh/keys/*.pub
chmod 644 ~/.ssh/known_hosts
