#!/bin/bash

add2list() {
	[ -z "$LIST" ] && LIST="$*" || LIST+=" OR $*"
}

LIST=""

case $1 in
	ads)
		add2list "(FROM:noreply@steampowered.com AND SUBJECT:\"on sale!\")"
		add2list "FROM:(email@empresas.dell.com OR email@home.dell.com)"
		add2list "FROM:*@ecampaigns.dell.com" # Dell
		add2list "FROM:*@insideapple.apple.com OR FROM:discover@new.itunes.com"
		add2list "FROM:Gopro@e-mail.gopro.com"
		add2list "FROM:Lenovo@enews.lenovo.com"
		add2list "FROM:compracerta@whr.com.br"
		add2list "FROM:comunicacao@clientesvivo.com.br"
		add2list "FROM:comunicado@montecarlo.com.br"
		add2list "FROM:contatohu@hotelurbano.com.br" # Hotel Urbano
		add2list "FROM:donotreply@mail.dolce-gusto.com"
		add2list "FROM:email.campaign@sg.booking.com"
		add2list "FROM:email@ricardoeletro.com.br"
		add2list "FROM:emailcenter@novidades.magazineluiza.com.br"
		add2list "FROM:info@e.mercadolivre.com.br"
		add2list "FROM:marketing@sampaingressos.com.br"
		add2list "FROM:nao-resposta@mastercard-email.com"
		add2list "FROM:news@mkt.americanas.com"
		add2list "FROM:noreply@getpocket.com"
		add2list "FROM:noreply@vivino.com"
		add2list "FROM:novidades@email.emkt.ingressorapido.com.br"
		add2list "FROM:offers@e.godaddy.com"
		add2list "FROM:oportunidades@ultrafarma.com.br"
		add2list "FROM:paypal@mail.paypal.com.br"
		add2list "FROM:promotion@aliexpress.com"
		add2list "FROM:store-news@amazon.com"
		add2list "FROM:vivara@news.vivara.com.br"
		add2list "LIST:07487d1456302a286cf9c4ccc.678209.list-id.mcsv.net" # TED
		add2list "LIST:<100012736.xt.local>" # Banco Inter
		add2list "LIST:<6204440.xt.local>" # Cobasi
		add2list "LIST:DX.com"
		add2list "LIST:cordial.1.13.sparkpostmail.com" # Humble Bundle
		add2list "LIST:cordial.1.545.sparkpostmail.com" # Fanatical
		add2list "LIST:fa32acc7a873c8ae79cceb5a0.243017.list-id.mcsv.net" # Recanto
		add2list "LIST:v3arcosdourados" # McDonalds
		add2list 'FROM:no.reply@brighttalk.com'
		;;

	ads_inbox)
		add2list "FROM:hello@discover.vivino.com"
		add2list "LIST:(<7205417.xt.local>)" # LATAM
		;;

	travel)
		add2list "SUBJECT:(\"Boarding Pass\" OR \"Bilhete de Embarque\")"
		add2list "FROM:(voegol@voegol.com.br)"
		add2list "FROM:(reservaciones@aeromexico.com)"
		;;

	old_junk)
		add2list "LABEL:advertisement"
		add2list "LABEL:alert"
		add2list "LABEL:collective-buying"
		add2list "LABEL:social-networks"
		LIST="($LIST) AND BEFORE:$(date +%F --date='-1 year')"
		;;

	*)
		echo "wat?"
		exit 1
		;;
esac

echo $LIST
echo $LIST | xsel -ib
