#!/bin/bash

function check_docker() {
	~/scripts/all/ping_docker -c 1 $1 > /dev/null
}

case $1 in
	backuppc) check_docker $1; RESULT=$? ;;
	*) echo "wat?" ;;
esac

curl -m 10 --retry 5 https://hc-ping.com/$2/$RESULT
