#!/bin/bash

read -d '' TRASH_LIST <<-EOF
.jline-jython.history
.jython-cache
.sqlite_history
.thumbnails
.wget-hsts
.xsel.log
.xsession-errors
.xsession-errors.old
EOF

HOME_REPO=$HOME/.local/share/housekeep
HOME_REPO_IGNOREFILE=$HOME/.config/housekeep_ignore

clean_trash() {
	DEST=/tmp/homeclean-$(date +"%F")
	mkdir -p $DEST

	cd $HOME
	echo -e "\nMoving to $DEST...\n"
	for ITEM in $TRASH_LIST; do
		if [ -e "$ITEM" ]; then
			echo "$ITEM"
			mv $ITEM $DEST/
		fi
	done
	echo -e "\nDone\n"
}

setup_housekeep_home() {
	GIT_CMD="echo git $(git_args home)"
	if [ ! -d $HOME_REPO ]; then
		$GIT_CMD init
		$GIT_CMD config core.excludesfile $HOME_REPO_IGNOREFILE
		$GIT_CMD commit --allow-empty -m "Initial commit"
	fi
}

git_args() {
	test $1 != "home" \
		&& echo "-C $HOME/$1" \
		|| echo "-C $HOME --git-dir=$HOME_REPO"
}

COMMAND=$1
shift

case $COMMAND in
	clean)
		clean_trash
		;;
	git)
		setup_housekeep_home
		exit
		case $1 in
			ansible|dotfiles|scripts|home)
				REPO=$1
				shift
				git $(git_args $REPO) $*
				;;
			*)
				for REPO in ansible dotfiles scripts home; do
					echo -e "========================================"
					echo -e "$REPO"
					echo -e "----------------------------------------"
					git $(git_args $REPO) $*
					echo ""
				done
				;;
		esac
		;;
	'') housekeep git status -s ;;
esac
