#!/bin/bash

read -d '' TRASH_LIST <<-EOF
.jline-jython.history
.jython-cache
.sqlite_history
.thumbnails
.wget-hsts
.xsel.log
.xsession-errors
.xsession-errors.old
EOF

clean_trash() {
	DEST=/tmp/homeclean-$(date +"%F")
	mkdir -p $DEST

	cd $HOME
	echo -e "\nMoving to $DEST...\n"
	for ITEM in $TRASH_LIST; do
		if [ -e "$ITEM" ]; then
			echo "$ITEM"
			mv $ITEM $DEST/
		fi
	done
	echo -e "\nDone\n"
}

git_args() {
	test $1 != "home" \
		&& echo "-C $HOME/$1" \
		|| echo "-C $HOME --git-dir=$HOME/.config/housekeep"
}

COMMAND=$1
shift

case $COMMAND in
	clean)
		clean_trash
		;;
	git)
		case $1 in
			status|pull|remote)
				for REPO in ansible dotfiles scripts home; do
					echo -e "========================================"
					echo -e "$REPO"
					echo -e "----------------------------------------"
					git $(git_args $REPO) $*
					echo ""
				done
				;;
			ansible|dotfiles|scripts|home)
				REPO=$1
				shift
				git $(git_args $REPO) $*
				;;
		esac
		;;
	gs) housekeep git status -s ;;
esac
