#!/bin/bash

case $1 in
	0|off|false|disable) ATT=1;;
	1|on|true|enable) ATT=0;;
	*) echo "Invalid argument!" && exit 1;;
esac

set -x
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=$ATT
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=$ATT
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=$ATT
