#!/bin/bash

COMMAND="/usr/bin/xdg-open $*"
HOST=10.3.3.5

run_pisa() {
	ssh -4 -x $HOST -C "export DISPLAY=:0.0 && $COMMAND"
}

if [ -e /dev/lxd ]; then
	if ping -4 -c 1 -W 1 $HOST > /dev/null 2>&1; then
		run_pisa
		exit 0
	elif [ -e /usr/bin/firefox ]; then
		/usr/bin/firefox $*
	fi
fi

if iwgetid | grep -q Lindt && ping -4 -c 1 -W 1 $HOST > /dev/null 2>&1; then
	run_pisa
	exit 0
fi

$COMMAND
