#!/bin/bash

COMMAND=$1
TARGET=$2
NAME=${TARGET%.*}
NETWORK=${TARGET##*.}
BACKUP_DIR=$HOME/backup/openwrt/$NETWORK/$NAME

test -z "$NAME" && echo "No machine defined" && exit 1
test "$NAME" = "$NETWORK" && echo "No network defined" && exit 2

case $COMMAND in
	backup)
		if ping -4 -c 1 -W 1 $TARGET > /dev/null 2>&1; then
			for DIR in etc www root; do
				mkdir -p $BACKUP_DIR/$DIR
				rsync -av --delete root@$TARGET:/$DIR/* $BACKUP_DIR/$DIR/
			done
			ssh $TARGET "opkg list-installed" > $BACKUP_DIR/installed
		fi
		;;

	*) ;;
esac
