#!/bin/bash

DISKS=$(sudo lsblk -d | grep "disk" | cut -d" " -f1)

PRINT="Disk;Power;Short;Long"

for DISK in $DISKS; do
	INFO="$(sudo smartctl -x /dev/$DISK)"
	POWER_ON=$(echo "$INFO" | grep "  Power-on Hours" | awk '{ print $4 }')
	test -z "$POWER_ON" && continue
	POWER_ON_DAYS="$((POWER_ON/24))"
	SHORT_STAMP=$(echo "$INFO" | grep " Short offline " | head -1 | awk '{ print  $(NF-1)}')
	SHORT_DIFF="$(((POWER_ON-SHORT_STAMP)/24))"
	LONG_STAMP=$(echo "$INFO" | grep " Extended offline " | head -1 | awk '{ print  $(NF-1)}')
	LONG_DIFF="$(((POWER_ON-LONG_STAMP)/24))"
	PRINT+="\n$DISK;$POWER_ON (${POWER_ON_DAYS}d);$SHORT_STAMP (-${SHORT_DIFF}d);$LONG_STAMP (-${LONG_DIFF}d)"
done

echo -e $PRINT | column -t -s ";"
