#!/bin/bash

#echo $* >> /tmp/ssh_proxy_command

HOST=$(echo $2 | sed "s/\..*//g")
PORT=$3

case $1 in
	lxc) IP=$(lxc list --format=yaml $HOST | grep -A 5 eth | grep "address: " | awk '{ print $2 }') ;;
	multipass) IP=$(multipass list --format csv | grep  $HOST | cut -d, -f3) ;;
	virsh) IP=$(virsh --connect qemu:///system domifaddr $HOST | awk -F'[ /]+' '{if (NR>2 && $5) print $5}' | tail -1) ;;
	*) echo "error" && exit 1 ;;
esac

nc $IP $PORT
