#!/bin/bash

COMMAND="VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json steam -forcedesktopscaling 2.0"
#COMMAND="steam"

[ -n "$1" ] && GAME=$1 || GAME=$(basename $0)

case $GAME in
	7d2d)        ID=251570 ;;
	moonlighter) ID=606150 ;;
	rdr2)        ID=1174180 ;;
	starbound)   ID=211820 ;;
esac
test -n "$ID" && COMMAND+=" steam://rungameid/$ID"

# Enable VR
#sudo setcap cap_sys_nice+eip \
	#/home/mopsifrog/.steam/steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher

# Limit card power
#sudo nvidia-smi -pl 100

set -x
xhost +local: > /dev/null
sudo su - mopsifrog -c "DISPLAY=:0 $COMMAND"
