#!/bin/bash
#timezone info at /usr/share/zoneinfo

CONFIG_FILE="$HOME/.config/timezones"

set_color() {
	if [ $1 -lt 8 ]; then
		COLOR=32
	elif [ $1 -ge 18 ]; then
		COLOR=34
	else
		COLOR=33
	fi
	echo -n "\033[0;${COLOR}m"
	echo -n "$2"
	echo -n "\033[0m"
}

[ -f $CONFIG_FILE ] && LIST=$(cat $CONFIG_FILE)

if [ -z "$(echo $LIST | xargs)" ]; then
	read -d '' LIST <<-EOF
	America/New_York,
	Asia/Calcutta,
	Australia/Canberra,
	Brazil/East,
	EST,
	Europe/London,
	Europe/Paris,
	Europe/Zurich,
	GMT,
	Mexico/General,
	US/Central,
	US/Eastern,
	US/Pacific,
	EOF
fi

[ -z "$*" ] && DT="now" || DT="$*"
OLDIFS=$IFS
IFS=$'\n'
for ITEM in $LIST; do
	CURR_TIME=$(TZ=$(echo $ITEM | cut -d, -f1) date +"%H:%M,%Z" --date "$DT")
	HOUR=$(echo $CURR_TIME | cut -d: -f1)
	TIMEZONE_LIST+="$(set_color $HOUR "$CURR_TIME,$ITEM")\n"
done
IFS=$OLDIFS

echo ""
echo -e "$TIMEZONE_LIST" | column -t -s, | sort
echo ""
