#!/bin/bash

PERSONAL=$HOME/wallpapers/in_use
test -d $PERSONAL && DIR=$PERSONAL || DIR=/usr/share/backgrounds
SAVE=/tmp/wallpaper
FILE=

get_list() {
	find $DIR -type f -printf %"f\n" | sort -h
}

case $1 in
	same) [ -f "$SAVE" ] && FILE="$(cat $SAVE)" || exit 1 ;;
	rofi)
		case $2 in
			'') rofi -show wallpaper -modi wallpaper:$0\ rofi\ list; exit ;;
			list)
				case $3 in
					'') get_list; exit ;;
					*) FILE="$DIR/$3" ;;
				esac ;;
		esac ;;
	*) FILE="$(find $DIR -type f | shuf -n 1)"; echo "$FILE" > $SAVE ;;
esac

/usr/bin/feh --bg-fill "$FILE"

