#!/bin/bash

finger_print() {
	if grep -q taskwarrior NEWS; then
		echo task
		return
	elif [ -f chrome2keepass.rb ]; then
		echo chrome2keepass
	else
		echo "unknown"
		return 1
	fi
}

title() {
	echo -e "\n $*\n=======================================================\n"
}

check_deps() {
	title Checking dependencies
	local TO_INSTALL=

	for DEP in $*; do
		echo -n "Checking $DEP... "
		if ! rpm -qa | grep -q $DEP; then
			echo "not installed!"
			TO_INSTALL+="$DEP "
		else
			echo "installed."
		fi
	done
	echo ""
	[ -n "$TO_INSTALL" ] && sudo yum install $TO_INSTALL
	echo ""
}

step() {
	title $*
	time $*
	echo -e "\nDone. Exit: $?\n"
}

PROJECT=$(finger_print)

case $PROJECT in
	task)
		check_deps libuuid-devel
		step cmake .
		step make
		step sudo make install
		;;

	chrome2keepass)
		check_deps rubygem-{sqlite3,builder}
		;;

	unknown)
		echo "Don't know"
		exit 1
		;;
esac

