#!/bin/bash

base_dir() {
	EXEC=${BASH_SOURCE[0]}
	if [ -h $EXEC ]; then
		LINK="$(readlink $EXEC)"
		[ "${LINK:0:1}" = "/" ] && EXEC="$LINK" || EXEC="$(dirname $EXEC)/$LINK"
	fi
	echo "$(cd $(dirname $EXEC); pwd)"
}

setup_git() {
	GIT_FILE=$HOME/.config/git/local
	if [ -f "$GIT_FILE" ]; then
		read -p "$GIT_FILE already exists. Overwrite? (y/n) " RESP
		[ "$RESP" = "y" ] && mv .$GIT_FILE{,\_$(date +%F_%H-%M-%S)} || return
	fi

	FULLNAME=$(getent passwd $LOGNAME | cut -d ":" -f 5)
	echo -n "Enter your full name [$FULLNAME]: "
	read NEWFULLNAME
	[ -n "$NEWFULLNAME" ] && FULLNAME=$NEWFULLNAME

	EMAIL="$LOGNAME@gmail.com"
	echo -n "Enter your email [$EMAIL]: "
	read NEWEMAIL
	[ -n "$NEWEMAIL" ] && EMAIL=$NEWEMAIL

	echo "[user]" > $GIT_FILE
	echo "    name = $FULLNAME" >> $GIT_FILE
	echo "    email = $EMAIL" >> $GIT_FILE
}

BASE_DIR="$(base_dir)"

# I always checkout the dotfiles repo in the same directory as the script one.
DOTFILES_DIR=${BASE_DIR/scripts/dotfiles}
if ! test -d $DOTFILES_DIR; then
	echo "There is no dotfiles directory. Cloning one..."
	git clone --recursive http://github.com/pfsmorigo/dotfiles.git $DOTFILES_DIR
fi

setup_git
