#!/bin/bash

DEST=/tmp/homeclean-$(date +"%F")
mkdir -p $DEST

read -d '' LIST <<-EOF
.jline-jython.history
.jython-cache
.sqlite_history
.thumbnails
.wget-hsts
.xsel.log
.xsession-errors
EOF

cd $HOME
echo -e "\nMoving to $DEST...\n"
for ITEM in $LIST; do
	if [ -e "$ITEM" ]; then
		echo "$ITEM"
		mv $ITEM $DEST/
	fi
done
echo -e "\nDone\n"
