#!/bin/bash

#screen -list | grep "tached)$" | sed 's/\t//;s/\s\+/ /;s/\./ /' | tr -d '()' | awk '{ print $1" "$3" "$2 }' | column -t

CURDIR="${PWD##*/}"

COUNT=0
SCREEN_LIST=$(screen -list | grep "tached)$" \
	| sed 's/\./;/;s/\t/;/g;s/^;//' | column -t -s';')

echo "$SCREEN_LIST" | grep -q "$CURDIR" \
	|| SCREEN_LIST="$(echo -e "$SCREEN_LIST\n(new) $CURDIR")"

echo ""
OLDIFS=$IFS
IFS=$'\n'
for SCREEN in $SCREEN_LIST; do
	COUNT=$(( $COUNT + 1 ))
	SCREEN_ARRAY[$COUNT]=$SCREEN
	printf "%5s) %s\n" $COUNT $SCREEN
done
IFS=$OLDIFS
echo ""

read -p "Pick one or type a new name: " PICK
[ -z "$PICK" ] && PICK=1
if [[ "$PICK" =~ ^[0-9]+$ ]]; then
	if [ $PICK -ge 1 -a $PICK -le $COUNT ]; then
		SCREEN_SELECTED=$(echo ${SCREEN_ARRAY[$PICK]} | cut -d' ' -f2)
	else
		echo "Out of the range!"
		exit 2
	fi
else
	SCREEN_SELECTED=$PICK
fi

[ "$SCREEN_SELECTED" = "$STY" ] && echo "Already in $SCREEN_SELECTED" && exit 3
screen -AOxRR $SCREEN_SELECTED
