#!/bin/bash

run_cmd() {
	echo $*
	$*
}

case $1 in
	owncloud|oc)
		run_cmd docker run \
			-v ~/owncloud:/usr/share/webapps/owncloud/data \
			--name owncloud \
			-p 80:80 \
			-p 443:443 \
			-d l3iggs/owncloud
		;;


	steam)
		echo "Remember to run ther server (use paprefs to set it)"
		run_cmd docker run -ti --rm=true \
			-e PULSE_SERVER=tcp:127.0.0.1:4713 \
			-e PULSE_COOKIE=/run/pulse/cookie \
			-e DISPLAY=${DISPLAY} \
			-v ~/.config/pulse/cookie:/run/pulse/cookie \
			-v /tmp/.X11-unix:/tmp/.X11-unix \
			-v /dev/shm:/dev/shm \
			-v /etc/machine-id:/etc/machine-id \
			-v ${HOME}/.cache/steam:/home/steam \
			steamos /bin/bash
			#-t -i tianon/steam /bin/bash
			#tianon/steam
		;;

	steam-old)
		#run_cmd docker run --name=steam --rm \
		run_cmd docker run -ti --rm \
			-v /tmp/.X11-unix:/tmp/.X11-unix \
			-v /dev/shm:/dev/shm \
			-v /run/user/${UID}/pulse:/run/user/${UID}/pulse \
			-v /etc/machine-id:/etc/machine-id \
			-v /var/lib/dbus:/var/lib/dbus \
			-v ~/.pulse:/home/${USER}/.pulse \
			-v ${HOME}/.cache/steam:/home/steam \
			-e DISPLAY=${DISPLAY} \
			steamos /bin/bash
			#-t -i tianon/steam /bin/bash
			#tianon/steam
		;;

	*)
		echo "wat?"
		;;
esac
