#!/bin/bash -x

DISK=manaus
[ -z "$DISK" ] && echo "Disk needed!" && exit 1


# Create basic directories
sudo mkdir -p /mnt/disk/$DISK-{boot,data,root,home}

# in order to lsyncd work for the /home directory
if ! grep -q "max_user_watches" /etc/sysctl.conf; then
	echo "fs.inotify.max_user_watches=524288" \
		| sudo tee -a /etc/sysctl.conf
	sysctl -p
fi

# crypttab
if ! sudo grep -q "luks-$DISK-home" /etc/crypttab; then
	echo -e "luks-$DISK-home /dev/mapper/$DISK-home nofail" \
		| sudo tee -a /etc/crypttab
fi

# fstab
if ! grep -q "/dev/mapper/$DISK-home" /etc/fstab; then
	echo -e "/dev/mapper/luks-$DISK-home /mnt/disk/$DISK-home ext4 defaults,nofail" \
		| sudo tee -a /etc/fstab
fi
if [ "$DISK" == "manaus" ] && ! grep -q "4E1AEA7B1AEA6007" /etc/fstab; then
	echo -e "/dev/disk/by-uuid/4E1AEA7B1AEA6007 /mnt/disk/manaus-data ntfs defaults,umask=000 0 0" \
		| sudo tee -a /etc/fstab
fi

# backlog

# install dropbox
