#!/bin/bash

REPO_DIR=$1
REPO_NAME=$2

[ -z "$REPO_DIR" ] && echo "Missing repo dir!" && exit 1
[ -z "$REPO_NAME" ] && echo "Missing repo name!" && exit 2

set -x
reposync -p $REPO_DIR -r $REPO_NAME -l
createrepo $REPO_DIR
