#!/bin/bash

URL=https://pgorelease.nianticlabs.com/plfe/version
VERFILE=/tmp/pgoversion

OLD_VERSION=$(cat $VERFILE 2> /dev/null )
VERSION=$(\curl -s $URL | xargs)
VERSION=${VERSION//[^0-9_.]/} # sanitize

echo $VERSION > $VERFILE

echo $VERSION
echo ""
[ "$VERSION" = "$OLD_VERSION" ] && echo "#ffffff" || echo "#9999ff"
