#! /bin/bash
# Sources: http://weechat.org/files/doc/devel/weechat_user.en.html#fifo_plugin

WEECHAT_FIFO=$HOME/.config/weechat/weechat_fifo
IRC_SERVER=irc.server.canonical-znc

echo "$IRC_SERVER */nick ${USER}_lunch" > $WEECHAT_FIFO

sleep 3
xfce4-screensaver-command -l

zenity --question --text "Start: $(date +%Hh%M)\n\nBack?"
if [ "$?" == "0" ]; then
	echo "$IRC_SERVER */nick $USER" > $WEECHAT_FIFO
fi

