#!/bin/bash

NAME=URxvt
SERVER=$1
COMMAND="bash"

TERMINALS="/usr/local/bin/urxvt /usr/bin/urxvt256c-ml /usr/bin/urxvt"
for TERM in $TERMINALS; do [ -e $TERM ] && EXEC=$TERM && break; done

if [ -n "$SERVER" ] && [ "$SERVER" != "local" ]; then
	NAME+="Remote"
	grep -q ^${SERVER}$ ~/.ssh/mosh && SSH="mosh" || SSH="ssh -tY"
	COMMAND="$SSH $SERVER"
fi

pgrep $(basename ${EXEC}d) > /dev/null || ${EXEC}d -q -f -o > /tmp/urxvtd.log 2>&1
set -xf
${EXEC}c -name $NAME -e sh -c "$COMMAND"
